[project]
name = "robotdataprocess"
version = "0.2"
authors = [
  { name="Daniel Butterfield", email="danielcbutter@gmail.com" },
  { name="Hanzhi Li", email="danielcbutter@gmail.com" },
  { name="Sandilya Sai Garimella", email="sgarimella34@gatech.edu"}
]
description = "A library for loading, saving, converting, and manipulating robotic datasets."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
dependencies = ["coverage",
                "evo",
                "matplotlib",

                # NumPy pin for successful build with ROS2
                "numpy<1.25; python_version >= '3.10'",
                "numpy; python_version <= '3.9'",

                "opencv-python",
                "rosbags",
                "scipy",
                "snakeviz",
                "tqdm",

                # Typeguard pin for successful build with ROS2
                "typeguard>=4.4.4; python_version >= '3.10'",
                "typeguard; python_version <= '3.9'",

                "typer",
                "pandas",
                "pillow",
                "pyyaml"]

# == License information TBD ==
# license = ""
# license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/lunarlab-gatech/robotdataprocess"
Issues = "https://github.com/lunarlab-gatech/robotdataprocess/issues"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.scripts]
robotdataprocess = "robotdataprocess.__main__:app"