input_bag: /media/dbutterfield3/T73/hercules_test_datasets_V1.1/ausenv_test1_checkpoints_CSLAM_2UAVUGV
output_bag: /media/dbutterfield3/T73/hercules_test_datasets_V1.1/ausenv_test1_checkpoints_CSLAM_2UAVUGV_ros1.bag
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manipulation/external_msgs
operation_to_run: 'convert_ros2_to_ros1'
operation_params:
  convert_ros2_to_ros1: