input_bag: /media/dbutterfield3/T73/hercules_datasets/V1.2/ausenv_test1_checkpoints_CSLAM_2UAVUGV_pruned
output_bag: /media/dbutterfield3/T73/hercules_datasets/V1.2/ausenv_test1_checkpoints_CSLAM_2UAVUGV_pruned.bag
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: 'convert_ros2_to_ros1'
operation_params:
  convert_ros2_to_ros1: