input_bag: /media/dbutterfield3/T73/hercules_test_datasets_V1.1/ausenv_test1_checkpoints_CSLAM_2UAVUGV
output_bag: /media/dbutterfield3/T73/hercules_test_datasets_V1.1/ausenv_test1_checkpoints_CSLAM_2UAVUGV_only60
external_msgs_path: /home/dbutterfield3/Research/rosbag_manipulation/external_msgs
operation_to_run: 'crop'
operation_params:
  crop:
    start_ts: 1747048365.868941009
    end_ts: 1747048425.868941009