# Input bag to use
input_bag:

# Path to save the output bag (if 'operation to run' is 'crop' or 'downsample')
output_bag:

# The path to repositories with additional message types to support
external_msgs_path: 

# This decides with of the operations below is run
operation_to_run: 

# Only the 'operation_to_run' operation parameters will be used
operation_params:

  # Generate histograms with an analysis of the hertz rates for a specific topic
  hertz_analysis:
    # Topic on which to analyze
    topic:

    # Output folder for placing generated figures
    output_folder: 

    # Tne number of expected messages on this topic, used for tqdm progress bars
    expected_msgs:

    # if 'topic' is '/tf' or '/tf_static', use this as the robot name to extract
    # the hertz rate of the following transform: '{robot_name}/odom_local'
    robot_name:

  # Crop the rosbag to only include message written into the bag within a certain timeframe
  crop:
    # Start timestamp in seconds for cropping the bag. If none is provided, will default to zero
    start_ts:

    # End timestamp in seconds for cropping the bag. If none is provided, no end timestamp will be set
    end_ts:

  # Downsample the hertz rates of topics in the bag & additionally resizes images to half their width/height.
  downsample:
    # Include all topics with the corresponding downsampling rate
    # A rate of 0.1 means save 1 out of every 10 messages
    topics: 
      Topic One: Downsample Rate
      Topic Two: Downsample Rate
      ...:
    
    # True if topics not mentioned in 'topics' should be included in the bag with no downsampling
    # False if they should not be included
    include_unmentioned_topics: 
