input_bag: /media/dbutterfield3/T73/hercules_datasets/V1.2/ausenv_test1_checkpoints_CSLAM_2UAVUGV_pruned
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: hertz_analysis
operation_params:
  hertz_analysis:
    topic: /hercules_node/Husky1/imu/imu
    output_folder: /home/dbutterfield3/Research/rosbag_manip/figures
    expected_msgs: 970602