input_bag: /media/dbutterfield3/T73/EuRoC_datasets/MH_01_easy_foxy
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: 'view_imu_data'
operation_params:
  view_imu_data:
    topic: /imu0
    output_folder: /home/dbutterfield3/Research/rosbag_manip/figures/IMU/EuRoC
    expected_msgs: 36820
    data_range: [0, 1000]