input_bag: /home/dbutterfield3/Desktop/GRaCo Dataset/aerial/ros2/aerial-01
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: 'view_imu_data'
operation_params:
  view_imu_data:
    topic: /gnss/imu
    output_folder: /home/dbutterfield3/Research/rosbag_manip/figures/IMU/GRaCo/aerial-01
    expected_msgs: 8177
    data_range: [0, 600]