input_bag: /media/dbutterfield3/T74/Hercules_datasets/V1.3/Drone1NED
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: 'view_imu_data'
operation_params:
  view_imu_data:
    topic: /imu
    output_folder: /home/dbutterfield3/Research/rosbag_manip/figures/IMU/HERCULES/Drone1
    expected_msgs: 168000
    data_range: [0, 4000]